# Generated by Django 3.0.7 on 2020-08-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modal',
            name='projectName',
            field=models.CharField(default='unnamed project', max_length=100),
        ),
    ]
