# Generated by Django 3.0.7 on 2020-08-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_modal_projectname'),
    ]

    operations = [
        migrations.CreateModel(
            name='DarkMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentMode', models.CharField(max_length=5)),
                ('path', models.CharField(max_length=20)),
                ('is_on', models.BooleanField()),
            ],
        ),
    ]
